function bgrad_list=dtrapdx(btrap,xyz_list,delta)
%ignore the vector part of the mag field

num_pts=size(xyz_list,1);

bgrad_list=sqrt(((trap_eval(btrap,xyz_list+repmat([delta,0,0],num_pts,1))...
                   -trap_eval(btrap,xyz_list-repmat([-delta,0,0],num_pts,1)))/(2*delta)).^2 ...
                +((trap_eval(btrap,xyz_list+repmat([0,delta,0],num_pts,1))...
                   -trap_eval(btrap,xyz_list-repmat([0,-delta,0],num_pts,1)))/(2*delta)).^2 ...
                +((trap_eval(btrap,xyz_list+repmat([0,0,delta],num_pts,1))...
                   -trap_eval(btrap,xyz_list+repmat([0,0,-delta],num_pts,1)))/(2*delta)).^2 ...
           );

end